### ISSUE TITLE
commented libvlc_audio_set_mute

### ISSUE THREAD

**Issue by vandanachadha** [jarrodwood/MediaScribe#1]
Some functions are commented in the code, any specific reason
for example:
libvlc_audio_set_mute in   partial class LibVLCLibrary

I got some legacy code and was trying to rebuild it in ,net4.5 and that uses this function.

**Comment by flippingkiwi** [comment]
Hello! I'm sorry, I don't quite understand your problem - when you say "I got some legacy code ... that uses this function" you mean that you have another project that uses VLC, and you are trying to use my version of LibVLCLibrary to make it work?

Please note that I am not the author of LibVLCLibrary, I simply used it in MediaScribe. It's also been 3-4 years since I've even looked at MediaScribe (since I was travelling and going through courses daily... these days I've moved on to other projects). There are likely much more complete, stable, modern libraries available now to interface with VLC.

Regarding why those functions are commented out, it would appear that I never used them, thus have never tested them, and had no need to expose them. Especially since upgrading from one version of VLC to another means the method signatures may change... why expose more functionality than I needed? :)

Do let me know if there's anything more I can help you with. Especially if you're using MediaScribe - I'm a little sad the project never took off in popularity! But then again, I had no interest in trying to market it.

**Comment by vandanachadha** [comment]
Thanks for your reply Jarrod.

Yes, I have another project which uses VLC and I am trying to use your version of LibVLC.Net to make it work. 

Have added in the missing function I needed, but still the video does not play. Console shows me some missing method error (but no method name) if I use the LibVLC.Net with a new version of libvlc (1.19). But if with an old version, then an error shows up of "procedure entry point of aout_DeviceGet" undefined. 

Do you remember which version of vlc worked for MediaScribe and whether you had it running on .net4.5.2

**Comment by vandanachadha** [comment]
Jarrod, your library worked after a few method additions, with VLC version 3.0.6....my eureka moment borrowed from you :-)

**Comment by flippingkiwi** [comment]
I'm glad you got it working. Though I think you would've been better off finding a newer and more complete VLC interop library for .Net... but perhaps there isn't any anymore. ^^ For reference, my last version of MediaScribe appears to have been using a nightly version of VLC 3.0.0 while it was still being developed.

Anyway, I'm happy to have helped!
